language: cpp
compiler: 
  - clang
  - gcc
os:
  - linux

sudo: required
dist: trusty
addons:
  apt:
    sources:  
      - ppa:ubuntu-toolchain-r/test      
      - llvm-toolchain-trusty-3.9
    packages:
      - clang-3.9
      - g++-6
      - gcc-6

before_script:
  - if [ ${CXX} = 'clang++' ]; then export CXX='clang++-3.9'; fi
  - if [ ${CXX} = 'g++' ]; then export CXX='g++-6'; fi
script:
  - cd build
  - cmake .. && make

notifications:
  email: false
